# Generated by Django 4.1.4 on 2022-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
