# Generated by Django 4.1.4 on 2022-12-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_api', '0005_alter_appointment_client_phohe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_phohe',
            field=models.CharField(max_length=13),
        ),
    ]
