# Generated by Django 4.1.4 on 2022-12-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_api', '0006_alter_appointment_client_phohe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
