# Generated by Django 4.1.4 on 2022-12-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_api', '0007_delete_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='client_phohe',
            new_name='client_phone',
        ),
    ]
